format_version: 5
pipelines:
#  test-pipeline-fb-2:
#    group: defaultGroup
#    label_template: ${COUNT}
#    lock_behavior: none
#    display_order: 1
#    materials:
#      git-fb-material-2:
#        plugin_configuration:
#          id: git.fb
#          version: 1.3.5
#        options:
#          url: https://github.com/artsiom-krauchanka/test-gocd-plugins
#          defaultBranch: main
#          shallow_clone: true
#          branchblacklist: main, dependabot/**
#    stages:
#      - scripts:
#          fetch_materials: true
#          keep_artifacts: false
#          clean_workspace: false
#          approval: success
#          jobs:
#            defaultJob:
#              timeout: 0
#              tasks:
#                - exec:
#                    arguments:
#                      - hello
#                    command: echo
#                    run_if: passed
  test-pipeline-pr-custom:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      git-fb-material-3:
        plugin_configuration:
          id: github.pr
          version: 1.4.1
        options:
          url: https://github.com/artsiom-krauchanka/test-gocd-plugins
          defaultBranch: main
          shallow_clone: true
    stages:
      - scripts:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval: success
          jobs:
            defaultJob:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - hello
                    command: echo
                    run_if: passed